# Which background of cell types to work with
background:
  KC:
  glia:

# Marker gene filtering settings
user_defined_log2FC_threshold:
  # genes above this threshold will not be considerd for the analysis
  KC:
    1.0
  glia:
    6.0
  peptides:
    3.0
log2FC_thresholds:
  # A separate UMAP will be computed on the result of removing genes
  # with an abs log2FC higher than this
  KC:
    [7.0, 3.0, 2.6, 2.5, 2.0, 1.5, 1.0, 0.5]
  glia:
    [10.0, 9.0, 8.0, 7.0, 6.5, 6.0, 5.5, 5.0, 4.5, 4.0]
max_clusters:
  # if a marker is gene is shared by this or more cell types
  # of the background, it is still considered for the analysis
  # because it is not a marker anymore within the background
  KC:
    3
  glia:
    5

# Dataset generation settings
raw: False
exclude_genes_file: None
batch_genes_file: "batch_effects.xlsx"
highly_variable_genes: False
h5ad_input: "h5ad/Preloom/All_Combined_No_ZT2_Wake.h5ad"

# Model settings
arch: ["NeuralNetwork"] # this is the selected model in this run.
# Implemented models:
#    * EBM
#    * Neural Network
#    * KNN ?
#    * RF ?

# Reproducibility settigs
seeds: [1000, 2000, 3000]

# Execution settings
ncores: -2

# Plotting settings
plotting_kwargs:
  barlimits: [0, 100]
  dpi: 600
  rotation: [90, 0]

extensions: ["png", "svg"]
cache: False
data_dir: "data/"
temp_data_dir: "data_conditions/"
results_dir: "results_conditions/"
template: "simple_condition_mapping.yaml"
DR_algorithm: ["TruncatedSVD"]
